adobe/aepsdk-edgeidentity-ios

Sources/Identity+PublicAPI.swift, Sources/IdentityConstants.swift, Sources/IdentityMap.swift
=> Minor public doc changes

.circleci/config.yml
Compare the SHA hash of the dowloaded CodeCov uploader script with the posted SHA values. If the check fails, fail the build. Otherwise, upload the coverage report.
=> Check the SHA hash of the CodeCov script

.circleci/config.yml
Update CodeCov upload step based on changes to CodeCov's documentation on how to validate the bash uploader script.
=> Update CodeCov upload step

README.md
=> Update SPM definition in README.md

.circleci/config.yml, AEPEdgeIdentity.xcodeproj/project.pbxproj, Makefile, Podfile, Podfile.lock, codecov.yml, tools/git-hooks/pre-commit
=> Update build scripts to fix the build archive step.

Sources/IdentityMap.swift
=> Update docs for IdentityMap.swift

AEPEdgeIdentity.podspec, AEPEdgeIdentity.xcodeproj/project.pbxproj, Podfile.lock, Sources/IdentityConstants.swift, Tests/Mocks/TestableExtensionRuntime.swift, Tests/UnitTests/IdentityPublicAPITests.swift
=> Bump up version for v1.0.1 release

.circleci/config.yml, Podfile, Podfile.lock, SampleApps/TestApp/AppDelegate.swift, Tests/Mocks/TestableExtensionRuntime.swift
=> Updated test dependencies

Documentation/api-reference.md, Documentation/getting-started.md, codecov.yml
Addition to https://github.com/adobe/aepsdk-edgeidentity-ios/pull/65 PR
=> [MOB-15818] Added objective-c samples for public classes

AEPEdgeIdentity.xcodeproj/project.pbxproj, Podfile.lock, SampleApps/TestApp/AdIdUtils.swift, SampleApps/TestApp/ContentView.swift
=> Update ad ID consent to align with sample app implementation

Makefile
=> Select test scheme from xcodeproj

Documentation/api-reference.md
Updates Documentation/api-reference with syntax and examples for the setAdvertisingIdentifier API in preparation for advertising id and consent preferences collection feature.
=> API docs for setAdvertisingIdentifier

Podfile, Podfile.lock, SampleApps/TestApp/AppDelegate.swift
=> Update test app dependencies for adid

AEPEdgeIdentity.podspec, AEPEdgeIdentity.xcodeproj/project.pbxproj, Podfile.lock, Sources/IdentityConstants.swift
New features and APIs will be added in this release so bumping the minor version.
=> Bump version to 1.1.0

Script/test-podspec.sh
=> Fix test-podspec script

.circleci/config.yml, .gitignore, AEPEdgeIdentity.podspec, AEPEdgeIdentity.xcodeproj/project.pbxproj, AEPEdgeIdentity.xcodeproj/xcshareddata/xcschemes/TestApptvOS.xcscheme, Makefile, Package.swift, Podfile, Podfile.lock, SampleApps/TestApp/AdIdUtils.swift, SampleApps/TestApp/AppDelegate.swift, SampleApps/TestApp/ContentView.swift, Script/test-SPM.sh, Script/test-podspec.sh, Tests/FunctionalTests/IdentityGetUrlVariablesTests.swift
=> [MOB-16629] Full tvOS support

.circleci/config.yml, README.md
Update SPM instruction and ci xcode version
=> Update SPM instruction and ci xcode version

AEPEdgeIdentity.podspec, AEPEdgeIdentity.xcodeproj/project.pbxproj, Podfile.lock, Sources/IdentityConstants.swift
=> Version bump and pod updates for tvOS support release

.circleci/config.yml, .gitignore, AEPEdgeIdentity.xcodeproj/project.pbxproj, AEPEdgeIdentity.xcodeproj/xcshareddata/xcschemes/AEPEdgeIdentity.xcscheme, AEPEdgeIdentity.xcodeproj/xcshareddata/xcschemes/FunctionalTests.xcscheme, AEPEdgeIdentity.xcodeproj/xcshareddata/xcschemes/UnitTests.xcscheme, Makefile, Script/test-SPM.sh
=> Update project settings and ci workflow

Documentation/api-reference.md
Update the api-reference documentation to state that an Identity Item's ID cannot be empty or nil, otherwise it is not added to the IdentityMap. This language matches the recent update to the Android api-reference.
The existing code already checks for empty IdentityItem identifiers and rejects them when adding to an IdentityMap. This PR simply updates the documentation to clearly state the existing behavior.
Relevant code where an empty id is checked:
https://github.com/adobe/aepsdk-edgeidentity-ios/blob/main/Sources/IdentityMap.swift#L133
https://github.com/adobe/aepsdk-edgeidentity-ios/blob/main/Tests/UnitTests/IdentityMapTests.swift#L86
https://github.com/adobe/aepsdk-edgeidentity-ios/blob/main/Tests/UnitTests/IdentityMapTests.swift#L205 …
=> Update API docs to state IdentityItem id cannot be empty or nil (resolves #92)

AEPEdgeIdentity.xcodeproj/project.pbxproj, Podfile, Podfile.lock
=> Update to latest production pods with tvOS support

LICENSE, Podfile, Podfile.lock, Script/test-podspec.sh
Update dependencies for testing
=> Update testing dependencies

.swiftlint.yml, Makefile, Podfile, Podfile.lock, SampleApps/TestApp/ContentView.swift, Sources/ECID.swift, Tests/.swiftlint.yml
Update SwiftLint to version 0.52.0 to support minimum deployment target 11
=> Update SwiftLint to 0.52.0

Podfile, Podfile.lock, Script/test-podspec.sh
=> Update core dependencies

Podfile, Podfile.lock, Script/test-podspec.sh
=> Dependency fixes

Makefile, Podfile, Podfile.lock, README.md, Script/test-podspec.sh
=> Update dependencies to latest released versions

AEPEdgeIdentity.xcodeproj/project.pbxproj, Makefile, Podfile, Podfile.lock, README.md, Script/test-podspec.sh
=> Update dev to latest main

AEPEdgeIdentity.podspec, AEPEdgeIdentity.xcodeproj/project.pbxproj, Makefile, Podfile, Podfile.lock, README.md, Script/test-podspec.sh, Sources/IdentityConstants.swift
v4.0.1 - add max version for podspec dependencies.
Pull main branch changes which were not on Staging.
=> v4.0.1 - add max version for podspec dependencies

Podfile, Podfile.lock
=> Merge main changes + staging pods
